In [4]:
# Step 1: Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Export to DataBase
from sqlalchemy import create_engine, types
from dotenv import dotenv_values

In [5]:
#pip install pandas pyreadstat

# Connect data base

In [6]:
# Load config
config = dotenv_values()

# define variables for the login
pg_user = config['POSTGRES_USER']  # align the key label with your .env file !
pg_pass = config['POSTGRES_PASS']
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
DB_URL = f"postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}"

engine = create_engine(DB_URL, echo=False)

## Dietary food data for Day 01

In [7]:
# Exporting the Dietary food day 1 data
df_dietary_food_first_day = pd.read_sas('F:\Susanna Course\Capstone_data\DR1IFF_L.xpt', format="xport", encoding="utf-8")

In [8]:
df_dietary_food_first_day.head(5)

,SEQN,WTDRD1,WTDR2D,DR1ILINE,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,...,DR1IM181,DR1IM201,DR1IM221,DR1IP182,DR1IP183,DR1IP184,DR1IP204,DR1IP205,DR1IP225,DR1IP226
0,130378.0,61366.555827,70554.222162,1.0,1.0,73.0,2.0,2.0,40.0,4.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
1,130378.0,61366.555827,70554.222162,2.0,1.0,73.0,2.0,2.0,40.0,4.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
2,130378.0,61366.555827,70554.222162,3.0,1.0,73.0,2.0,2.0,40.0,4.0,...,5.397605e-79,5.397605e-79,5.397605e-79,3.000000e-03,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
3,130378.0,61366.555827,70554.222162,4.0,1.0,73.0,2.0,2.0,40.0,4.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
4,130378.0,61366.555827,70554.222162,5.0,1.0,73.0,2.0,2.0,40.0,4.0,...,6.530000e-01,7.000000e-03,5.397605e-79,1.418000e+00,1.890000e-01,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,1.000000e-03

In [9]:
df_dietary_food_first_day.shape

(100116, 84)

In [10]:
# Step 1: Select only the columns with meaningful values
columns_to_keep = ['SEQN', 'DR1CCMNM', 'DR1CCMTX', 'DR1FS', 'DR1IGRMS', 'DR1IKCAL']
df_dietary_food_first_day = df_dietary_food_first_day[columns_to_keep]


# Step 2: Rename the columns
df_dietary_food_first_day = df_dietary_food_first_day.rename(columns={
    'SEQN': 'seqn_no',
    'DR1CCMNM': 'food_no',
    'DR1CCMTX': 'food_type',
    'DR1FS': 'food_source',
    'DR1IGRMS': 'food_gms',
    'DR1IKCAL': 'energy_kcal'
})

# Step 3: Changing the data type of 'seqn_no' to int
df_dietary_food_first_day['seqn_no'] = df_dietary_food_first_day['seqn_no'].astype(int)

In [11]:
# Group by 'seqn_no' and sum 'food_gms' and 'energy_kcal' for each participant
agg_df_01 = df_dietary_food_first_day.groupby('seqn_no')[['food_gms', 'energy_kcal']].sum().reset_index()

In [12]:
agg_df_01.columns

Index(['seqn_no', 'food_gms', 'energy_kcal'], dtype='object')

Export as csv

In [ ]:
#export Day1 food as csv to data/dietary_data

file_path = "../data/dietary_data/dietary_food_data_day_01.csv" 

try:
    df_dietary_food_first_day.to_csv(file_path, index=False, encoding='utf-8')
    print(f"DataFrame successfully saved to: {file_path}")
except Exception as e:
    print(f"Error saving DataFrame to CSV: {e}")

DataFrame successfully saved to: ../data/dietary_data/dietary_food_data_day_01.csv

In [180]:
# Now building the URL with the values from the .env file
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

engine = create_engine(url, echo=False)

In [ ]:
# Creating table and adding Day1 food data to the database
df_dietary_food_first_day.to_sql(name = 'dietary_food_day_01', con=engine, schema='capstone_group_3',if_exists='replace',index=False)

116

## Dietary food data for Day 02

In [13]:
# Exporting the Dietary food day 2 data
df_dietary_food_second_day = pd.read_sas('F:\Susanna Course\Capstone_data\DR2IFF_L.xpt', format="xport", encoding="utf-8")

In [14]:
df_dietary_food_second_day

,SEQN,WTDRD1,WTDR2D,DR2ILINE,DR2DRSTZ,DR2EXMER,DRABF,DRDINT,DR2DBIH,DR2DAY,...,DR2IM181,DR2IM201,DR2IM221,DR2IP182,DR2IP183,DR2IP184,DR2IP204,DR2IP205,DR2IP225,DR2IP226
0,130378.0,61366.555827,70554.222162,1.0,1.0,49.0,2.0,2.0,45.0,2.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
1,130378.0,61366.555827,70554.222162,2.0,1.0,49.0,2.0,2.0,45.0,2.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
2,130378.0,61366.555827,70554.222162,3.0,1.0,49.0,2.0,2.0,45.0,2.0,...,5.397605e-79,5.397605e-79,5.397605e-79,6.000000e-03,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
3,130378.0,61366.555827,70554.222162,4.0,1.0,49.0,2.0,2.0,45.0,2.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
4,130378.0,61366.555827,70554.222162,5.0,1.0,49.0,2.0,2.0,45.0,2.0,...,1.360000e-01,5.397605e-79,5.397605e-79,9.800000e-02,2.100000e-02,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88027,142310.0,47870.215680,51601.585149,6.0,1.0,91.0,2.0,2.0,37.0,2.0,...,5.000000e-03,1.000000e-03,3.000000e-03,9.000000e-03,2.000000e-03,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
88028,142310.0,47870.215680,51601.585149,7.0,1.0,91.0,2.0,2.0,37.0,2.0,...,2.050000e-01,3.000000e-03,5.397605e-79,1.740000e-01,3.100000e-02,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
88029,142310.0,47870.215680,51601.585149,8.0,1.0,91.0,2.0,2.0,37.0,2.0,...,2.475000e+00,1.300000e-02,3.000000e-03,3.008000e+00,3.510000e-01,5.397605e-79,4.000000e-03,5.397605e-79,5.397605e-79,5.397605e-79
88030,142310.0,47870.215680,51601.585149,9.0,1.0,91.0,2.0,2.0,37.0,2.0,...,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
88031,142310.0,47870.215680,51601.585149,10.0,1.0,91.0,2.0,2.0,37.0,2.0,...,5.429000e+00,3.000000e-02,5.397605e-79,2.811000e+00,1.450000e-01,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79

In [15]:
# Step 1: Select only the columns with meaningful values for Day2
columns_to_keep = ['SEQN', 'DR2CCMNM', 'DR2CCMTX', 'DR2FS', 'DR2IGRMS', 'DR2IKCAL']
df_dietary_food_second_day = df_dietary_food_second_day[columns_to_keep]


# Step 2: Rename the columns
df_dietary_food_second_day = df_dietary_food_second_day.rename(columns={
    'SEQN': 'seqn_no',
    'DR2CCMNM': 'food_no',
    'DR2CCMTX': 'food_type',
    'DR2FS': 'food_source',
    'DR2IGRMS': 'food_gms',
    'DR2IKCAL': 'energy_kcal'
})

# Step 3: Changing the data type of 'seqn_no' to int
df_dietary_food_second_day['seqn_no'] = df_dietary_food_second_day['seqn_no'].astype(int)

In [16]:
df_dietary_food_second_day.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88032 entries, 0 to 88031
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   seqn_no      88032 non-null  int64
 1   food_no      88032 non-null  float64
 2   food_type    88032 non-null  float64
 3   food_source  81295 non-null  float64
 4   food_gms     87778 non-null  float64
 5   energy_kcal  87778 non-null  float64
dtypes: float64(5), int64(1)
memory usage: 4.0 MB

In [17]:
#export Day2 food as csv to data/dietary_data

file_path = "../data/dietary_data/dietary_food_data_day_02.csv" 

try:
    df_dietary_food_second_day.to_csv(file_path, index=False, encoding='utf-8')
    print(f"DataFrame successfully saved to: {file_path}")
except Exception as e:
    print(f"Error saving DataFrame to CSV: {e}")

DataFrame successfully saved to: ../data/dietary_data/dietary_food_data_day_02.csv

In [18]:
# Now building the URL with the values from the .env file
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

engine = create_engine(url, echo=False)

In [19]:
# creating table and adding Day2 food data to the database

df_dietary_food_second_day.to_sql(name = 'dietary_food_day_02', con=engine, schema='capstone_group_3',if_exists='replace',index=False)

32

In [20]:
# Group by 'seqn_no' and sum 'food_gms' and 'energy_kcal' for each participant
agg_df_02 = df_dietary_food_first_day.groupby('seqn_no')[['food_gms', 'energy_kcal']].sum().reset_index()
agg_df_02

      seqn_no  food_gms  energy_kcal
0      130378   3662.08       1740.0
1      130379   4697.95       2741.0
2      130380   4537.50       1995.0
3      130381   1995.40       1676.0
4      130382   1533.98       1222.0
...       ...       ...          ...
6746   142303   1966.30        280.0
6747   142304   1454.75       1569.0
6748   142307   2675.00       1609.0
6749   142309   2196.00       4651.0
6750   142310   1437.99       1305.0

[6751 rows x 3 columns]

Calculating avg for food_gms and energy_Kcal for each seqn_no for both days

In [21]:
# Now let's avg the food data on each seqn_no

# Concatenate the two dataframes
df_food = pd.concat([agg_df_01, agg_df_02])

# List of columns that need to be aggregated
food_columns = [
    'food_gms', 'energy_kcal'
]

# Select only the relevant nutrient columns and group by 'seqn_no'
df_food_filtered = df_food[['seqn_no'] + food_columns]

# Group by 'seqn_no' and calculate the mean for all nutrient columns
df_food_avg = df_food_filtered.groupby('seqn_no').agg('mean').reset_index()

In [22]:
df_food_avg

      seqn_no  food_gms  energy_kcal
0      130378   3662.08       1740.0
1      130379   4697.95       2741.0
2      130380   4537.50       1995.0
3      130381   1995.40       1676.0
4      130382   1533.98       1222.0
...       ...       ...          ...
6746   142303   1966.30        280.0
6747   142304   1454.75       1569.0
6748   142307   2675.00       1609.0
6749   142309   2196.00       4651.0
6750   142310   1437.99       1305.0

[6751 rows x 3 columns]