In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, types # Export to DataBase

# read XPT file - Smoking - Cigarette Use (first-hand)
df_smoking = pd.read_sas("../data/questionaire_data/SMQ_L.xpt", format="xport", encoding="utf-8")
df_smoking

,SEQN,SMQ020,SMQ040,SMD641,SMD650,SMD100MN,SMQ621,SMD630,SMAQUEX2
0,130378.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0
1,130379.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0
2,130380.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,130384.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,130385.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...
9010,142305.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9011,142307.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0
9012,142308.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9013,142309.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9014,142310.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,1.0

In [2]:
print("Smoking Questionaire Data Info:")
df_smoking.info() 

# SMQ020 - Smoked at least 100 cigarettes in life
# SMQ040 - Do you now smoke cigarettes?

# SMD641 - # days smoked cigs during past 30 days
# SMD650 - Avg # cigarettes/day during past 30 days
# SMD100MN - Cigarette Menthol indicator
# SMQ621 - Cigarettes smoked in entire life
# SMD630 - Age first smoked whole cigarette
# SMAQUEX2 - Questionnaire Mode Flag -> drop

Smoking Questionaire Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9015 entries, 0 to 9014
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      9015 non-null   float64
 1   SMQ020    8135 non-null   float64
 2   SMQ040    3243 non-null   float64
 3   SMD641    273 non-null    float64
 4   SMD650    1185 non-null   float64
 5   SMD100MN  1175 non-null   float64
 6   SMQ621    772 non-null    float64
 7   SMD630    23 non-null     float64
 8   SMAQUEX2  9015 non-null   float64
dtypes: float64(9)
memory usage: 634.0 KB

In [ ]:
# Define the columns you want to keep and their new names
smoking_columns_to_keep_and_rename = {
    'SEQN': 'Participant_ID',                     # Keep SEQN for merging
    'SMQ020': 'Smoked_100_Cigs_Lifetime',          # New name for "Smoked at least 100 cigarettes in life"
    'SMQ040': 'Smokes_Now'                         # New name for "Do you now smoke cigarettes?"
}

# Select only the desired columns from the original DataFrame
df_smoking_selected = df_smoking[list(smoking_columns_to_keep_and_rename.keys())].copy()

# Rename the columns in the new DataFrame
df_smoking_selected.rename(columns=smoking_columns_to_keep_and_rename, inplace=True)


# --- Verification Steps ---
print("--- Selected and Renamed Smoking Data Info ---")
df_smoking_selected.info()

print("\n--- First few rows of the new DataFrame ---")
print(df_smoking_selected.head())

--- Selected and Renamed Smoking Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9015 entries, 0 to 9014
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Participant_ID            9015 non-null   float64
 1   Smoked_100_Cigs_Lifetime  8135 non-null   float64
 2   Smokes_Now                3243 non-null   float64
dtypes: float64(3)
memory usage: 211.4 KB

--- First few rows of the new DataFrame ---
   Participant_ID  Smoked_100_Cigs_Lifetime  Smokes_Now
0        130378.0                       1.0         3.0
1        130379.0                       1.0         3.0
2        130380.0                       2.0         NaN
3        130384.0                       2.0         NaN
4        130385.0                       2.0         NaN

In [4]:
import pandas as pd
import numpy as np

try:
    df_smoking_2nd = pd.read_sas("../data/questionaire_data/SMQFAM_L.xpt", format="xport", encoding="utf-8")
    print("--- Data loaded successfully. Initial data preview: ---")
    print(df_smoking_2nd.head())
except FileNotFoundError:
    print("Error: File not found. Please check your file path.")
    exit()

--- Data loaded successfully. Initial data preview: ---
       SEQN        SMD460  SMD470
0  130378.0  5.397605e-79     NaN
1  130379.0  5.397605e-79     NaN
2  130380.0  5.397605e-79     NaN
3  130381.0  5.397605e-79     NaN
4  130382.0  5.397605e-79     NaN

In [5]:
# Step 1: Replace invalid small float values
df_smoking_2nd['SMD460'] = pd.to_numeric(df_smoking_2nd['SMD460'], errors='coerce')
df_smoking_2nd['SMD470'] = pd.to_numeric(df_smoking_2nd['SMD470'], errors='coerce')

# Step 2: Round if necessary and cast to Int64 to support NA
df_smoking_2nd['SMD460'] = df_smoking_2nd['SMD460'].round().astype('Int64')
df_smoking_2nd['SMD470'] = df_smoking_2nd['SMD470'].round().astype('Int64')

# Step 3:  Rename for clarity
df_smoking_2nd.rename(columns={
    'SEQN': 'Participant_ID',
    'SMD460': 'Household_Smokers_Total',
    'SMD470': 'Household_Smokers_Indoors'
}, inplace=True)

# Step 4: Inspect again
print("Second-Hand Smoking Questionaire Data Info:")
df_smoking_2nd.info()

Second-Hand Smoking Questionaire Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11933 entries, 0 to 11932
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Participant_ID             11933 non-null  float64
 1   Household_Smokers_Total    10624 non-null  Int64
 2   Household_Smokers_Indoors  2604 non-null   Int64
dtypes: Int64(2), float64(1)
memory usage: 303.1 KB

In [7]:
df_smoking_2nd

       Participant_ID  Household_Smokers_Total  Household_Smokers_Indoors
0            130378.0                        0                       <NA>
1            130379.0                        0                       <NA>
2            130380.0                        0                       <NA>
3            130381.0                        0                       <NA>
4            130382.0                        0                       <NA>
...               ...                      ...                        ...
11928        142306.0                        0                       <NA>
11929        142307.0                        2                          0
11930        142308.0                        0                       <NA>
11931        142309.0                        1                          0
11932        142310.0                        0                       <NA>

[11933 rows x 3 columns]

In [ ]:
# --- Merge the two DataFrames ---
# Use pd.merge to combine them based on the common 'Participant_ID' column.

df_smoking_combined = pd.merge(
    df_smoking_selected,
    df_smoking_2nd,
    on='Participant_ID',  # The common column to merge on
    how='outer'           # The type of merge to perform
)

# --- Verification ---
print("--- Combined Smoking Data Info ---")
df_smoking_combined.info()

print("\n--- First few rows of Combined Smoking Data ---")
print(df_smoking_combined.head())

--- Combined Smoking Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11933 entries, 0 to 11932
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Participant_ID             11933 non-null  float64
 1   Smoked_100_Cigs_Lifetime   8135 non-null   float64
 2   Smokes_Now                 3243 non-null   float64
 3   Household_Smokers_Total    10624 non-null  Int64
 4   Household_Smokers_Indoors  2604 non-null   Int64
dtypes: Int64(2), float64(3)
memory usage: 489.6 KB

--- First few rows of Combined Smoking Data ---
   Participant_ID  Smoked_100_Cigs_Lifetime  Smokes_Now  \
0        130378.0                       1.0         3.0
1        130379.0                       1.0         3.0
2        130380.0                       2.0         NaN
3        130381.0                       NaN         NaN
4        130382.0                       NaN         NaN

   Household_Smokers_Total  Household_Smokers_Indoors
0                        0                       <NA>
1                        0                       <NA>
2                        0                       <NA>
3                        0                       <NA>
4                        0                       <NA>

In [10]:
# To see how the merge handled different participants, you can check specific rows
print(df_smoking_combined[df_smoking_combined['Participant_ID'] == 130380])

   Participant_ID  Smoked_100_Cigs_Lifetime  Smokes_Now  \
2        130380.0                       2.0         NaN

   Household_Smokers_Total  Household_Smokers_Indoors
2                        0                       <NA>

In [ ]:
df_smoking_combined = df_smoking_combined.convert_dtypes()

In [12]:
df_smoking_combined

,Participant_ID,Smoked_100_Cigs_Lifetime,Smokes_Now,Household_Smokers_Total,Household_Smokers_Indoors
0,130378,1,3,0,<NA>
1,130379,1,3,0,<NA>
2,130380,2,<NA>,0,<NA>
3,130381,<NA>,<NA>,0,<NA>
4,130382,<NA>,<NA>,0,<NA>
...,...,...,...,...,...
11928,142306,<NA>,<NA>,0,<NA>
11929,142307,1,3,2,0
11930,142308,2,<NA>,0,<NA>
11931,142309,2,<NA>,1,0
11932,142310,1,3,0,<NA>

In [13]:
# export as csv
file_path = "../data/questionaire_data/cleaned_smoking_combined.csv" 

try:
    df_smoking_combined.to_csv(file_path, index=False, encoding='utf-8')
    print(f"DataFrame successfully saved to: {file_path}")
except Exception as e:
    print(f"Error saving DataFrame to CSV: {e}")

DataFrame successfully saved to: ../data/questionaire_data/cleaned_smoking_combined.csv

In [14]:
from dotenv import dotenv_values

config = dotenv_values()

# define variables for the login
pg_user = config['POSTGRES_USER']  # align the key label with your .env file !
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
pg_pass = config['POSTGRES_PASS']

# Now building the URL with the values from the .env file
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

engine = create_engine(url, echo=False)

In [15]:
df_smoking_combined.to_sql(name = 'smoking_combined_questionaire_data', con=engine, schema='capstone_group_3',if_exists='replace',index=False)

933